export const PRODUCT_CATEGORIES: string[] = [
  'Vidrios / Vidrios Blindados Antiestáticos',
  'Productos Originales',
  'Cargadores Tipo C',
  'Cargadores iPhone',
  'Cargadores V8',
  'Cabezales',
  'Cables TC x TC',
  'Cables V8',
  'Cables USB x Tipo C',
  'Cables iPhone',
  'Power Bank',
  'Audífonos',
  'SmartWatch',
  'Radios',
  'Parlantes',
  'Controles',
  'Soportes de Celular',
  'Máquinas',
  'Accesorios de PC',
  'Línea Hogar',
  'Memorias USB',
  'Micro SD',
  'Memorias de Música Económica',
];
